version: 2

sources:
  - name: staging
    database: de-zoo
    schema: trips_data_all_hw

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata

  - name: raw_nyc_tripdata
    database: "{{ env_var('DBT_BIGQUERY_PROJECT', 'dtc_zoomcamp_2025') }}"
    schema:   "{{ env_var('DBT_BIGQUERY_SOURCE_DATASET', 'raw_nyc_tripdata') }}"
    tables:
      - name: ext_green_taxi
      - name: ext_yellow_taxi